# Generated by Django 3.2.8 on 2021-10-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
                ('whatsapp', models.CharField(max_length=11)),
            ],
        ),
    ]
