# Generated by Django 3.2.8 on 2021-10-25 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empreendedor', '0002_auto_20211025_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('receita_despesa', models.CharField(default='D', max_length=1)),
                ('fixo_variavel', models.CharField(default='F', max_length=1)),
                ('empreendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendedor.empreendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=80)),
                ('data_vencimento', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('data_pagamento', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('valor', models.FloatField(default=0)),
                ('descricao', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendedor.categoria')),
                ('empreendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendedor.empreendedor')),
            ],
        ),
    ]
